import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import StoreProvider from "./StoreProvider";
import Sidebar from "./components/Sidebar/Sidebar";
import GlobalLoading from "./global-loading";
import { Suspense } from "react";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import GlobalError from "./global-error";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next JS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        <Suspense fallback={<GlobalLoading />}>
          <ErrorBoundary fallback={<GlobalError />}>
            <StoreProvider>
              <header id="navbar">
                <Navbar />
              </header>
              <main className="min-h-screen flex">
                <Sidebar />
                <div className="flex flex-col items-center w-full">
                  {children}
                  <Footer />
                </div>
              </main>
            </StoreProvider>
          </ErrorBoundary>
        </Suspense>
      </body>
    </html>
  );
}
